# Generated by Django 3.1 on 2021-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
